---
# intentionally leaving 00-clean-deps to prevent re-creating the venv every time
- import_playbook: 01-setup-deps.yaml # noqa: name[play]
- import_playbook: bat.yaml # noqa: name[play]
- import_playbook: caddy.yaml # noqa: name[play]
- import_playbook: postgres.yaml # noqa: name[play]
- import_playbook: rclone.yaml # noqa: name[play]
