---
# intentionally leaving 00-clean-deps to prevent re-creating the venv every time
- import_playbook: 01-setup-deps.yaml # noqa: name[play]
- import_playbook: bat.yaml # noqa: name[play]
- import_playbook: caddy.yaml # noqa: name[play]
- import_playbook: postgresql-client.yaml # noqa: name[play]
- import_playbook: rclone.yaml # noqa: name[play]
- import_playbook: simple-packages.yaml # noqa: name[play]
- import_playbook: syncthing.yaml # noqa: name[play]
- import_playbook: tailscale.yaml # noqa: name[play]
