---
- import_playbook: bin.yaml # noqa: name[play]
- import_playbook: caddy.yaml # noqa: name[play]
- import_playbook: charasheet.yaml # noqa: name[play]
- import_playbook: checkout.yaml # noqa: name[play]
- import_playbook: code.yaml # noqa: name[play]
- import_playbook: ghost.yaml # noqa: name[play]
- import_playbook: git.yaml # noqa: name[play]
- import_playbook: goatcounter.yaml # noqa: name[play]
- import_playbook: lyon-transports.yaml # noqa: name[play]
- import_playbook: manuels.yaml # noqa: name[play]
- import_playbook: media.yaml # noqa: name[play]
- import_playbook: miniflux.yaml # noqa: name[play]
- import_playbook: nextcloud-aio.yaml # noqa: name[play]
- import_playbook: paperless-ngx.yaml # noqa: name[play]
- import_playbook: portainer.yaml # noqa: name[play]
- import_playbook: privatebin.yaml # noqa: name[play]
- import_playbook: shortener.yaml # noqa: name[play]
- import_playbook: stirling-pdf.yaml # noqa: name[play]
- import_playbook: test_headers.yaml # noqa: name[play]
- import_playbook: voice-pipeline.yaml # noqa: name[play]
- import_playbook: wallabag.yaml # noqa: name[play]
- import_playbook: watchtower.yaml # noqa: name[play]
- import_playbook: ynab.yaml # noqa: name[play]
