---
- name: Media
  hosts: home
  gather_facts: false
  tasks:
    - name: Docker
      ansible.builtin.include_role:
        name: docker

  vars:
    docker_app_name: media
    plex_claim: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      61633832616461636362643838353961353962393662346235616664343635363864616366346331
      3663316133316336333032626165303763396539303539300a323935663564386165636237666536
      38393939383461653564333232666565383837306465363833336636666535306438306132323066
      6635653763376534640a373861383531636438353138386133333430376262356635373333666237
      34663664613631393139313731623836626439613535623365343233363937616265
    transmission_password: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      34386433633862613963376431303435363964366138616135643266643661633835656466643466
      3962383731643061383663666130343136333462643733620a653234373937633164326230316363
      32326137376263366163666433303363393464646639363166663933346364663437353439333965
      3163646264326437310a333737333766306234366435613335303632373231306566386566333533
      36663764396230353939306238373132363137376231383063343839653537613037336162366261
      30336462653132656433323237613362323135623665336461376434303335353136333262653365
      636134613535663365316265636163653335
    sonarr_api_key: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      31393436633730653965363164333165326434353133666164336463653264623337373438346332
      3261323037663432343266336332336139626234656130380a366432323935356134333936373934
      66313232353132363439373338623331313832313463336432656466626632306465326664343731
      3431653135333631340a333962656132663065393737306261366237326532643338303832363463
      64346136336438363238336237396231343064633464353934383835653132613363383833376166
      3934616366616264626232303561666533386435666166366632
    radarr_api_key: !vault |-
      $ANSIBLE_VAULT;1.1;AES256
      65653435326663343566643664373737356438666466326566303733393132343637343266666664
      3738326336613035373039636133316466656332303463620a646163366538343633616234326539
      36333038393731316464323631373239356532306366353961656533643863656135633634386364
      3833373537656164650a346139343762326166653634396230333133343930623263306561356361
      61666438653664633764303263366434653436623366386364613631623862383364313434626638
      3830616364616363396134346135383862643733616333656434
