on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  ansible:
    name: run ansible
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v5.2.0
        with:
          # Version range or exact version of Python or PyPy to use, using SemVer's version range syntax. Reads from .python-version if unset.
          python-version: 3
          # Used to specify a package manager for caching in the default directory. Supported values: pip, pipenv, poetry.
          cache: pip
          # Set this option if you want the action to check for the latest available version that satisfies the version spec.
          check-latest: true
      - name: Install ansible
        run: pip install ansible
      - name: Run ansible
        run: |
          export KEY_FILE=$(mktemp)
          echo "${{ secrets.DEPLOY_KEY }}" > $KEY_FILE
          ansible-playbook playbooks/all.yaml
